monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - routing # On déclare notre canal personnalisé ici
        - scheb_two_factor
        - security
        - mailer

when@dev:
    monolog:
        handlers:
            # On ajoute notre handler rotatif dédié au routage
            routing_handler:
                type: rotating_file
                path: "%kernel.logs_dir%/routing.log"
                level: info
                channels: ["routing"]
                max_files: 30
            # LOGS DU BUNDLE 2FA
            scheb_two_factor:
                type: stream
                path: "%kernel.logs_dir%/scheb_two_factor.log"
                level: debug
                channels: ["scheb_two_factor"]
            # LOGS DE SÉCURITÉ SYMFONY
            security:
                type: stream
                path: "%kernel.logs_dir%/security.log"
                level: debug
                channels: ["security"]
            # LOGS DU MAILER
            mailer:
                type: stream
                path: "%kernel.logs_dir%/mailer.log"
                level: debug
                channels: ["mailer"]
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!routing"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!deprecation"]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
